www_base: /srv/www/catchall
docroot: "{{ www_base }}/public"
www_log_dir: "{{ www_base }}/log"
www_tmp_dir: "{{ www_base }}/tmp"
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_fpm_state: started
php_fpm_enabled_on_boot: true
php_fpm_pool_user: "$pool"
php_fpm_pool_group: "$pool"
php_date_timezone: "UTC"
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-fpm
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-pdo
  - php-pecl-apcu
  - php-xml
php_mysql_package: php-mysqlnd
mysql_enabled_on_startup: true
mysql_packages:
  - mariadb
  - mariadb-server
mysql_daemon: mariadb
mysql_user: mysql
mysql_config_file: /etc/my.cnf
mysql_config_include_dir: /etc/my.cnf.d
mysql_supports_innodb_large_prefix: true
mysql_slow_query_log_enabled: false
mysql_slow_query_log_file: /var/log/mariadb/mariadb-slow.log
#mysql_log: /var/log/mariadb/mariadb.log
mysql_log: ""
mysql_log_error: /var/log/mariadb/mariadb-error.log
mysql_log_file_group: mysql
mysql_socket: /var/lib/mysql/mysql.sock
mysql_pid_file: /var/run/mariadb/mariadb.pid
mysql_syslog_tag: mariadb
mysql_root_password: password

webdirs:
  - "public"
  - "tmp"
  - "log"
  - "session"

sites:
  - name: isp3vps2
    fqdn: isp3vps2.example.com
    uid: 6601
    php: false
    mysql: false
    mypasswd: nopassword
    host: isp3vps2.example.com
  - name: isp3site2
    fqdn: isp3site2.example.com
    uid: 6602
    php: true
    mysql: true
    mypasswd: password
    host: isp3vps2.example.com
  - name: dvwa
    fqdn: dvwa.example.com
    uid: 6603
    php: true
    mysql: true
    mypasswd: p@ssw0rd
    host: isp3vps2.example.com
  - name: foo
    fqdn: foo.example.com
    uid: 6604
    php: true
    mysql: true
    mypasswd: foopass
    host: isp3vps3.example.com
